// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType1;
//
//    var welcome1 = Welcome1.FromJson(jsonString);

namespace QuickType1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome1
    {
        [JsonProperty("cast")]
        public string Cast { get; set; }

        [JsonProperty("crew")]
        public string Crew { get; set; }

        [JsonProperty("id")]
        public Id Id { get; set; }
    }

    public partial struct Id
    {
        public long? Integer;
        public string String;

        public static implicit operator Id(long Integer) => new Id { Integer = Integer };
        public static implicit operator Id(string String) => new Id { String = String };
    }

    public partial class Welcome1
    {
        public static Welcome1[] FromJson(string json) => JsonConvert.DeserializeObject<Welcome1[]>(json, QuickType1.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome1[] self) => JsonConvert.SerializeObject(self, QuickType1.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                IdConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class IdConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Id) || t == typeof(Id?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                    var integerValue = serializer.Deserialize<long>(reader);
                    return new Id { Integer = integerValue };
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new Id { String = stringValue };
            }
            throw new Exception("Cannot unmarshal type Id");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Id)untypedValue;
            if (value.Integer != null)
            {
                serializer.Serialize(writer, value.Integer.Value);
                return;
            }
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            throw new Exception("Cannot marshal type Id");
        }

        public static readonly IdConverter Singleton = new IdConverter();
    }
}
